[versions]
# 核心库
agp = "8.13.2"
datastore = "1.2.0"
kotlin = "2.3.0"
ksp = "2.3.4"
compose-bom = "2025.12.01"
compose-compiler = "1.5.15"
core-ktx = "1.17.0"
lifecycle-runtime-ktx = "2.10.0"
activity-compose = "1.12.2"

# 官方库
foundation = "1.10.0"
accompanist-permissions = "0.37.3"
biometric = "1.4.0-alpha05"
camerax = "1.5.2"
material-icons-extended = "1.7.8"
navigation-compose = "2.9.6"
room = "2.8.4"
android-tools = "31.13.2"
room-gradle-plugin = "2.8.4"
desugar-jdk-libs = "2.1.5"
# 测试相关
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"

# 三方库
lunar = "1.7.7"
pinyin = "0.4.0"
retrofit = "3.0.0"
mlkit = "17.3.0"
zxing-core = "3.5.4"
coil = "3.3.0"
coil-zoomable = "0.18.0"

[libraries]
# 核心库
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" } # 支持kotlin
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" } # 组件支持生命周期管理
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" } # 支持在activity中嵌入compose组件
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" } # 统一管理compose相关依赖版本

# 官方库
material3 = { module = "androidx.compose.material3:material3" } # material3风格的官方组件库及主题
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" } # icon扩展库
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" } # 支持viewmodel
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" } # 支持组件间导航
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" } # 简化权限请求
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" } # 简化生物认证
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" } # 简化相机调用
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" } # 相机生命周期管理
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" } # 相机视图容器
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" } # 简化数据库访问
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" } # room支持kotlin
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" } # room支持根据注解自动生成对应实现
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" } # 官方脱糖库，对低版本支持Java 8+ API
# 调试相关
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" } # 支持compose组件预览
# 测试相关
junit = { module = "junit:junit", version.ref = "junit" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

# 三方库
lunar = { module = "cn.6tail:lunar", version.ref = "lunar" } # 计算农历日期与节日
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" } # colil核心库
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" } # 加载网络图片
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil" } # 加载视频帧
coil-zoomable = { module = "me.saket.telephoto:zoomable-image-coil3", version.ref = "coil-zoomable" } # 图片缩放/加载大图
pinyin = { module = "com.github.houbb:pinyin", version.ref = "pinyin" } # 汉字转拼音
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" } # 网络请求库
retrofit-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" } # 支持网络响应结果转为指定类对象
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing-core" } # 二维码生成/识别（效率低）
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit" } # 二维码识别（基于机器学习）

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradle-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room-gradle-plugin" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
weui-android-compose-application = { id = "weui.android.compose.application" }
weui-android-compose-library = { id = "weui.android.compose.library" }
weui-android-room = { id = "weui.android.room" }

[bundles]
camerax = ["camera-camera2", "camera-lifecycle", "camera-view"]
retrofit = ["retrofit", "retrofit-converter"]
datastore = ["datastore-core", "datastore-preferences"]
coil = ["coil-compose", "coil-network", "coil-video"]
